#Main models for cylinder performance (Touch and Towards)
datum=read.csv (file.choose())#TouchFinal data file
library(lme4)
library(lmerTest)
results<-lmer(Cylinder.Touch~Sex+Order*Reward*Preference.Index+(1|Dog),data=datum) #three-way interaction not significant so removed 
summary(results)
results<-lmer(Cylinder.Touch~Sex+Order+Reward*Preference.Index+(1|Dog),data=datum) #interaction of reward and preference index not significant so removed
summary(results)
results<-lmer(Cylinder.Touch~Sex+Order*Reward+Preference.Index+(1|Dog),data=datum) #interaction of order and reward not significant so removed
summary(results)
results<-lmer(Cylinder.Touch~Sex+Order*Preference.Index+Reward+(1|Dog),data=datum) #interaction of order and preference index not significant so removed
summary(results)
results<-lmer(Cylinder.Touch~Sex+Order+Preference.Index+Reward+(1|Dog),data=datum) #final model with main effects (minimal adequate model)
summary(results)

datum=read.csv(file.choose()) #TowardsFinal data file 
results<-lmer(Cylinder.Towards~Sex+Order*Reward*Preference.Index+(1|Dog),data=datum) #three-way interaction not significant so removed
summary(results)
results<-lmer(Cylinder.Towards~Sex+Order+Reward*Preference.Index+(1|Dog),data=datum) #interaction of reward and preference index not significant so removed
summary(results)
results<-lmer(Cylinder.Towards~Sex+Order*Reward+Preference.Index+(1|Dog),data=datum) #interaction of order and reward not significant so removed
summary(results)
results<-lmer(Cylinder.Towards~Sex+Order*Preference.Index+Reward+(1|Dog),data=datum) #interaction of order and preference index not significant so removed
summary(results)
results<-lmer(Cylinder.Towards~Sex+Order+Reward+Preference.Index+(1|Dog),data=datum) #final model with main effects (minimal adequate model)
summary(results)

#Exploratory models for DIAS and cylinder performance (Touch and Towards)
datum=read.csv(file.choose()) #TouchFinal data file
#Touch(treat)
results=glm(Cylinder.Touch~Sex*DIAS, subset=c(Reward=="t"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex+DIAS, subset=c(Reward=="t"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex*BR, subset=c(Reward=="t"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex+BR, subset=c(Reward=="t"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex*A, subset=c(Reward=="t"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex+A, subset=c(Reward=="t"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex*R, subset=c(Reward=="t"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex+R, subset=c(Reward=="t"),data=datum) 
summary(results)
#Touch(ball)
results=glm(Cylinder.Touch~Sex*DIAS, subset=c(Reward=="b"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex+DIAS, subset=c(Reward=="b"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex*BR, subset=c(Reward=="b"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex+BR, subset=c(Reward=="b"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex*A, subset=c(Reward=="b"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex+A, subset=c(Reward=="b"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex*R, subset=c(Reward=="b"),data=datum) 
summary(results)
results=glm(Cylinder.Touch~Sex+R, subset=c(Reward=="b"),data=datum) 
summary(results)

datum=read.csv(file.choose()) #TowardsFinal data file
#Towards(treat)
results=glm(Cylinder.Towards~Sex*DIAS, subset=c(Reward=="t"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex+DIAS, subset=c(Reward=="t"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex*BR, subset=c(Reward=="t"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex+BR, subset=c(Reward=="t"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex*A, subset=c(Reward=="t"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex+A, subset=c(Reward=="t"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex*R, subset=c(Reward=="t"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex+R, subset=c(Reward=="t"),data=datum)
summary(results)
#Towards(ball)
results=glm(Cylinder.Towards~Sex*DIAS, subset=c(Reward=="b"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex+DIAS, subset=c(Reward=="b"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex*BR, subset=c(Reward=="b"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex+BR, subset=c(Reward=="b"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex*A, subset=c(Reward=="b"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex+A, subset=c(Reward=="b"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex*R, subset=c(Reward=="b"),data=datum)
summary(results)
results=glm(Cylinder.Towards~Sex+R, subset=c(Reward=="b"),data=datum)
summary(results)